SELECT * FROM BBS;

CREATE TABLE BBSW (
    NO NUMBER(10) NOT NULL,
    BBS_NO NUMBER(10),
    WRITER VARCHAR(255),
    CONTENT VARCHAR(1024),
    REGDATE DATE,
    WCOUNT NUMBER(4) DEFAULT 0,
    OK NUMBER(1) DEFAULT 1,
    PRIMARY KEY (NO)
    );

CREATE SEQUENCE BBSW_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO BBSW VALUES(bbsw_seq.nextval, 1, 'TEST', 'TEST', SYSDATE, 0, 1);
COMMIT;

SELECT * FROM BBSW;

ALTER TABLE BBS ADD FILENAME VARCHAR2(255);

DESC BBS;

ALTER TABLE BBSW ADD (LIKE_COUNT NUMBER DEFAULT 0, DISLIKE_COUNT NUMBER DEFAULT 0);
ALTER TABLE BBSW ADD PARENT_NO NUMBER;



