CREATE TABLE BBS (
    NO NUMBER(10) NOT NULL,
    TITLE VARCHAR(255),
    WRITER VARCHAR(255),
    CONTENT VARCHAR(4000),
    REGDATE DATE,
    OK NUMBER(1) DEFAULT 1,
    PRIMARY KEY (NO)
    );
    
// 마지막에 COMMIT을 실행해줘야 메인 DB로 넘어간다.
COMMIT;
    
SELECT * FROM BBS;
    
CREATE SEQUENCE BBS_SEQ START WITH 1 INCREMENT BY 1; // 시퀀스 생성
    
// BBS_SEQ.NEXTVAL : 순서대로 생성
INSERT INTO BBS VALUES(BBS_SEQ.NEXTVAL, 'DB TEST' , 'TEST', 'DB TEST', SYSDATE,1);
INSERT INTO BBS VALUES(BBS_SEQ.NEXTVAL, 'DB TEST' , 'TEST', 'DB TEST', SYSDATE,1);

